### ISSUE TITLE
Headers are case sensetive despite RFC 2616

### ISSUE THREAD

**Issue by wyattjsmith1** [myndocs/kotlin-oauth2-server#38]
**Describe the bug**
In particular, I noticed this with the "Authorization" header. When authorizing Identities, the authorization must be lower case because of the implementation of [`BasicAuthorizer#extractCredentials`](https://github.com/myndocs/kotlin-oauth2-server/blob/4bb63405f9ef345ebe97126979b4937105ee4245/oauth2-server-core/src/main/java/nl/myndocs/oauth2/request/auth/BasicAuthorizer.kt#L9`). [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) states  

> Field names are case-insensitive

**To Reproduce**

1. Create ktor project with the default setup in the README.md
2. Try to authenticate with `curl -X GET -H 'authorization: Basic Zm9vOmJhcg==' -i 'http://localhost:8080/oauth/authorize?response_type=code&client_id=testapp&redirect_uri=https://localhost:8080/callback'`. The request should work as expected.
3. Now, change the case of the header to `curl -X GET -H 'Authorization: Basic Zm9vOmJhcg==' -i 'http://localhost:8080/oauth/authorize?response_type=code&client_id=testapp&redirect_uri=https://localhost:8080/callback'`. This request will fail with a 401 because of the `BasicAuthorizer` class.

**Expected behavior**
The request should succeed with a 302 as if it was lowercase.

**Additional context**
All headers should be case insensitive, and they are usually capitalized as a standard.

**Comment by adhesivee** [comment]
Thanks for the bug report. I have fixed it and merged into develop. 
I will release this in the coming days.

**Comment by adhesivee** [comment]
This is now released with 0.3.1
