### ISSUE TITLE
Allow extension of grant types

### ISSUE THREAD

**Issue by palmfjord** [myndocs/kotlin-oauth2-server#43]
Oauth2 supports extending a server with custom grant types, as described i.e. here:

> OAuth 2.0 also supports extension grant types allowing organizations to define their own custom grant types to support additional client types or to provide a bridge between OAuth and existing systems.
https://www.oauth.com/oauth2-servers/differences-between-oauth-1-2/user-experience-alternative-token-issuance-options/)

**Problem**:
Allowed grant types seem to be hard-coded i.e. [in the CallRouter](https://github.com/myndocs/kotlin-oauth2-server/blob/2b7df5fb8fa3480150aa83a66e5e740161d7b91b/oauth2-server-core/src/main/java/nl/myndocs/oauth2/CallRouter.kt#L44-L62) as of now.

**Solution**
There should be away of configuring your own custom grant types and their corresponding flows.

**Alternatives**
N/A

**Other info**
(Have taken this lib for a spin now, looks really awesome so far!)

**Comment by adhesivee** [comment]
Closing this. Extension is now possible. It should be done in a more friendly way (#46)
