### ISSUE TITLE
Ability to add metadata to access and refresh tokens

### ISSUE THREAD

**Issue by palmfjord** [myndocs/kotlin-oauth2-server#50]
**Is your feature request related to a problem? Please describe.**
I can't pass any metadata along with the access token, i.e. to the token store. Also there's some fields missing that could be useful if one is using JWTs as ATs - such as the `jti` (token id) and `aud` (audience).

**Describe the solution you'd like**
A way to pass metadata, i.e. a `String -> Any` map on the AT class. Also possibly add an optional id field to the AT, for the use case where your access token isn't an id itself.

**Describe alternatives you've considered**
- Make the Access Token class open so it can be extended
- Let the access token be an interface rather than a data class

**Additional context**
Maybe the same for refresh tokens. Possibly also for `TokenInfo` so metadata can be shown in the token info endpoint? (unsure whether that's desired or not but it sure would be handy)

**Comment by adhesivee** [comment]
It is possible to implement it, but the metadata can only be provided by [AccessTokenConverter](https://github.com/myndocs/kotlin-oauth2-server/blob/develop/oauth2-server-core/src/main/java/nl/myndocs/oauth2/token/converter/AccessTokenConverter.kt) or [RefreshTokenConverter](https://github.com/myndocs/kotlin-oauth2-server/blob/develop/oauth2-server-jwt/src/main/java/nl/myndocs/convert/JwtRefreshTokenConverter.kt). Would this fit your use-case?

For `jti` and `aud` I am not sure what to fill as defaults. It could be implemented by creating an own [JwtBuilder](https://github.com/myndocs/kotlin-oauth2-server/blob/develop/oauth2-server-jwt/src/main/java/nl/myndocs/convert/JwtBuilder.kt) and pass it to [JwtAccessTokenConverter](https://github.com/myndocs/kotlin-oauth2-server/blob/develop/oauth2-server-jwt/src/main/java/nl/myndocs/convert/JwtAccessTokenConverter.kt)

**Comment by palmfjord** [comment]
@adhesivee Valid point. In my use case it's totally ok for the AccessTokenConverter to generate the jti, which is what i need for now, but moving forward it would of lock me in. A thought that just struck me - wouldn't it make more sense to pass `Identity` to `AccessTokenConverter` and let that have metadata also, rather than the username only?

Imo `jti` and `aud` could be null by default, since everyone won't use them. My plan is to use client id as `aud` and that's available in the AT converter as of now.

**Comment by adhesivee** [comment]
@palmfjord That is a good idea. `Identity` can be passed to `AccessTokenConverter`. `Identity` should also be passed to `AccessToken` instead of username.

**Comment by palmfjord** [comment]
@adhesivee sounds very reasonable!

**Comment by adhesivee** [comment]
Please check #53 if this supports your use-case

**Comment by palmfjord** [comment]
@adhesivee yup, looks good 👌

**Comment by adhesivee** [comment]
Fixed with `0.5.0`
