### ISSUE TITLE
How to encapsulate requests into the "authenticated" part in ktor?

### ISSUE THREAD

**Issue by sergiocasero** [myndocs/kotlin-oauth2-server#68]
Let me start with an issue.

In ktor, when you want to add one auth system (basic, for example) yo can do something like this:

```kotlin
install(Authentication) {
        basic(AUTH) {
            realm = REALM

            validate { credentials ->
                if (credentials.name == AUTH_USER && credentials.password == AUTH_PASSWORD) {
                    UserIdPrincipal(credentials.name)
                } else {
                    null
                }
            }
        }
    }
```

And then, to specify which requests need auth, we do that:

```kotlin
routing {
        authenticate(AUTH) {
            route("/api") {
                post("/test") { call.respond("Hello from authenticated part!") }
            }
        }
    }
```

How can we specify this behaviour with this lib?

**Comment by adhesivee** [comment]
Thanks for your ticket. 
This project only implements the server side of oauth2. 
For now at least the client side is not supported, you could take a look how ktor implements the client side of oauth https://ktor.io/servers/features/authentication/oauth.html.

But it could be a good feature to add, to have this autoconfigured.

**Comment by velastroll** [comment]
Hi @sergiocasero,
i've got the same issue, and i'm solving this intercepting each request and checking the token identity in function of the uri.
You can see more at https://ktor.io/advanced/pipeline/route.html

**Comment by adhesivee** [comment]
OAuth2 clients won't be supported.
If this change in future new issue can be made, or this ticket can be re-opened
