### ISSUE TITLE
Bintray is deprecated

### ISSUE THREAD

**Issue by velastroll** [myndocs/kotlin-oauth2-server#82]
**Is your feature request related to a problem? Please describe.**
There is no way to import this lib by gradle/maven because of bintray is deprecated and downloader of dependencies doesn't work.

**Describe the solution you'd like**
A good solution would be update readme, and describe a HOWTO's list to generate and include the .jars from the .zip file. So people can use and download this lib without of an external-dependencies-server.

**Describe alternatives you've considered**
- Update HowTo's to don't depend of external business
- Bintray alternatives

**Additional context**
TY for your work!
Best regards

**Comment by adhesivee** [comment]
Good point, I think it is possible to publish mvn packages on GitHub these days (note to self: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry)
I will take a look at this coming days.

**Comment by adhesivee** [comment]
Package have been uploaded to [GitHub packages](https://github.com/orgs/myndocs/packages?repo_name=kotlin-oauth2-server).
Unfortunately a `GITHUB_TOKEN` is required for this in order to pull in dependencies.

I will have to look further into mvn repositories which can be hosted publicly.

**Comment by ghost** [comment]
Hi @adhesivee, please consider moving to maven central.

**Comment by ulfryk** [comment]
Hi @adhesivee - any plans to move it to maven central?

**Comment by adhesivee** [comment]
Looking into deployment of maven central

**Comment by adhesivee** [comment]
Version 0.7.1 is now deployed on central https://repo.maven.apache.org/maven2/nl/myndocs/.
